"""FHIR R4 / HL7-oriented EHR interop helpers."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional


def to_fhir_patient(
    *,
    patient_id: int,
    full_name: Optional[str] = None,
    gender: Optional[str] = None,
    birth_date: Optional[str] = None,
    phone: Optional[str] = None,
    email: Optional[str] = None,
) -> Dict[str, Any]:
    given, family = "", ""
    if full_name:
        parts = full_name.split()
        given = parts[0]
        family = parts[-1] if len(parts) > 1 else ""
    return {
        "resourceType": "Patient",
        "id": str(patient_id),
        "meta": {"lastUpdated": datetime.now(timezone.utc).isoformat()},
        "name": [{"use": "official", "family": family, "given": [given] if given else []}],
        "gender": (gender or "unknown").lower(),
        "birthDate": birth_date,
        "telecom": [
            *( [{"system": "phone", "value": phone}] if phone else [] ),
            *( [{"system": "email", "value": email}] if email else [] ),
        ],
    }


def to_fhir_observation_lab(
    *,
    patient_id: int,
    report_id: int,
    summary: Optional[str],
    report_type: str = "laboratory",
) -> Dict[str, Any]:
    return {
        "resourceType": "Observation",
        "id": f"lab-{report_id}",
        "status": "final",
        "category": [
            {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                        "code": "laboratory",
                        "display": "Laboratory",
                    }
                ]
            }
        ],
        "code": {"text": report_type},
        "subject": {"reference": f"Patient/{patient_id}"},
        "valueString": summary or "",
        "note": [{"text": "Generated by AI Healthcare Assistant — clinician review required."}],
    }


def to_fhir_appointment(
    *,
    appointment_id: int,
    patient_id: int,
    doctor_id: int,
    scheduled_at: str,
    status: str,
    reason: Optional[str] = None,
) -> Dict[str, Any]:
    status_map = {
        "scheduled": "booked",
        "cancelled": "cancelled",
        "completed": "fulfilled",
        "checked_in": "arrived",
    }
    return {
        "resourceType": "Appointment",
        "id": str(appointment_id),
        "status": status_map.get(status, "booked"),
        "description": reason or "Consultation",
        "start": scheduled_at,
        "participant": [
            {"actor": {"reference": f"Patient/{patient_id}"}, "status": "accepted"},
            {"actor": {"reference": f"Practitioner/{doctor_id}"}, "status": "accepted"},
        ],
    }


def parse_hl7_oru_lite(message: str) -> Dict[str, Any]:
    """
    Minimal HL7 v2 ORU^R01 parser for demo lab ingest.
    Segments separated by newlines; fields by |.
    """
    segments = [s.strip() for s in message.replace("\r", "\n").split("\n") if s.strip()]
    pid = {}
    obx_list: List[Dict[str, str]] = []
    for seg in segments:
        fields = seg.split("|")
        if not fields:
            continue
        if fields[0] == "PID":
            pid = {
                "id": fields[3] if len(fields) > 3 else "",
                "name": fields[5] if len(fields) > 5 else "",
            }
        if fields[0] == "OBX":
            obx_list.append(
                {
                    "set_id": fields[1] if len(fields) > 1 else "",
                    "value_type": fields[2] if len(fields) > 2 else "",
                    "observation_id": fields[3] if len(fields) > 3 else "",
                    "value": fields[5] if len(fields) > 5 else "",
                    "units": fields[6] if len(fields) > 6 else "",
                }
            )
    return {"message_type": "ORU_R01", "patient": pid, "observations": obx_list}


def fhir_capability_statement() -> Dict[str, Any]:
    return {
        "resourceType": "CapabilityStatement",
        "status": "draft",
        "date": datetime.now(timezone.utc).date().isoformat(),
        "kind": "instance",
        "fhirVersion": "4.0.1",
        "format": ["json"],
        "rest": [
            {
                "mode": "server",
                "resource": [
                    {"type": "Patient", "interaction": [{"code": "read"}, {"code": "search-type"}]},
                    {"type": "Observation", "interaction": [{"code": "create"}, {"code": "read"}]},
                    {"type": "Appointment", "interaction": [{"code": "read"}, {"code": "create"}]},
                ],
            }
        ],
        "implementation": {
            "description": "AI Healthcare Assistant FHIR/HL7 interop (scaffold)",
            "url": "/api/v1/fhir",
        },
    }
