input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [audit] {
    mutate { add_tag => ["audit"] }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "ai-healthcare-%{+YYYY.MM.dd}"
  }
}
