events {}
http {
  upstream frontend { server frontend:8911; }
  upstream backend { server backend:8000; }

  server {
    listen 80;
    location /api/ { proxy_pass http://backend; }
    location /docs { proxy_pass http://backend; }
    location /health { proxy_pass http://backend; }
    location / { proxy_pass http://frontend; }
  }
}
